POST http://localhost:8080/analyse
Accept: application/json

{
    "webUrl":"https://en.wikipedia.org/w/index.php?title=Special:UserLogin&returnto=Main+Page"
}
###
GET http://localhost:8080/analyse
Accept: application/json
###
GET http://localhost:8080/analyse/1
Accept: application/json